### ISSUE TITLE
Error: No API key set.

### ISSUE THREAD

**Issue by chuy-pulido** [mountainMath/cancensus#202]
I'm trying to run the using cansensus examples 1. "Income: A first look" and 2. "Language Diversity in Canada"

In 2. "Get census data" step, I run the instruction as provided: langs_cma <- get_census(dataset, level = "CMA", regions = regions_list10, vectors = language_vectors, geo_format = NA, labels = "short")
 
In return, I get the following error message:  Error in get_census(dataset, level = "CMA", regions = regions_list10,  : 
  No API key set. Use set_api_key('<your API ket>`) to set one, or set_api_key('<your API ket>`, install = TRUE) to save is permanently in our .Renviron.

However, I confirm that I have entered my API KEY in a previous step using set_cancensus_api_key(<your_api_key>', install = TRUE)

Am I skipping any step, or perhaps need to run some updates to be able to continue? Thanks.

**Comment by mountainMath** [comment]
Hmm. This should not happen. In older versions of cancensus setting the API key required to restart the session so the API key would get loaded, but this should not be necessary any more. Although it could be that this only got fixed in the current development version. Can you restart your session and see if the problem persists?

**Comment by chuy-pulido** [comment]
I went ahead and restarted the session but I couldn't solve the problem. Then I proceeded to uninstall/install again both R and RStudio, just in case there was a problem with the software version. Unfortunately this did not solve the problem. Here's a snippet of what comes back:

> data <- get_census(dataset = 'CA16', level="Regions", vectors=median_income_vectors, regions=regions, geo_format = NA, labels='short')
Error in get_census(dataset = "CA16", level = "Regions", vectors = median_income_vectors,  : 
  No API key set. Use set_api_key('<your API ket>`) to set one, or set_api_key('<your API ket>`, install = TRUE) to save is permanently in our .Renviron.

> set_cancensus_api_key(CensusMapper_7888067764348ab658e92f167abca2a1, overwrite=FALSE, install=TRUE)
Error: An existing Censusmapper API key is already saved. You can overwrite it with the argument overwrite=TRUE.

Thank you.

**Comment by chuy-pulido** [comment]
Ok. So I followed your instructions and finally came through it. To answer the questions above:

1. After entering `Sys.getenv("CM_API_KEY")` I confirm my API key came back (but the data still wasn't loading).
2. The cancensus version I am using is cancensus_0.5.5
3. I believe my network is under a firewall protection, but I don't think it is possible to disconnect from it.

After reviewing the cancensus documentation online, I used the code `options(cancensus.api_key = "CensusMapper_your_api_key")` and installed the 'sf' and 'geojsonsf' packages. Seems like this fixed the issue and now I am able to load the data.

Thank you.

**Comment by chuy-pulido** [comment]
Ok. So I followed your instructions and finally came through it. To answer the questions above:

1. After entering `Sys.getenv("CM_API_KEY")` I confirm my API key came back (but the data still wasn't loading).
2. The cancensus version I am using is cancensus_0.5.5
3. I believe my network is under a firewall protection, but I don't think it is possible to disconnect from it.

After reviewing the cancensus documentation online, I used the code `options(cancensus.api_key = "CensusMapper_your_api_key")` and installed the 'sf' and 'geojsonsf' packages. Seems like this fixed the issue and now I am able to load the data.

Thank you.

**Comment by mountainMath** [comment]
Thanks for the info, it *should* work without setting the options variable. Will check into this to see if I can reproduce this with fix it.
